notifications:
  email: false

language: go
go:
  - "1.12"
  - "1.13"

install: false

env:
  - GO111MODULE=on GOFLAGS=-mod=vendor

before_script:
- make install-linter

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
