notifications:
  email: false

language: go
go:
  - "1.12"
  - "1.x"
install: true

before_script:
- make install-linter

jobs:
  include:
    - stage: lint
      script: make lint
      env:
        - GO111MODULE=on
        - GOFLAGS=-mod=vendor
    - stage: test
      script: make test
      env:
        - GO111MODULE=on
        - GOFLAGS=-mod=vendor
