notifications:
  email: false

language: go
go:
  - "1.12"
  - "master"

install: true

env:
  - GO111MODULE=on GOFLAGS=-mod=vendor

before_script:
  - make install-linter

script:
  - make lint
  - make test
